// 100 of the most common / useful beginner Korean words.
// One is surfaced per day on the dashboard, rotating by date.

export interface KoreanWord {
  hangul: string;
  romanization: string;
  meaning: string;
}

export const KOREAN_WORDS: KoreanWord[] = [
  { hangul: "안녕", romanization: "annyeong", meaning: "hello / hi" },
  { hangul: "네", romanization: "ne", meaning: "yes" },
  { hangul: "아니요", romanization: "aniyo", meaning: "no" },
  { hangul: "감사합니다", romanization: "gamsahamnida", meaning: "thank you" },
  { hangul: "사랑", romanization: "sarang", meaning: "love" },
  { hangul: "물", romanization: "mul", meaning: "water" },
  { hangul: "밥", romanization: "bap", meaning: "rice / meal" },
  { hangul: "사람", romanization: "saram", meaning: "person" },
  { hangul: "집", romanization: "jip", meaning: "house / home" },
  { hangul: "학교", romanization: "hakgyo", meaning: "school" },
  { hangul: "친구", romanization: "chingu", meaning: "friend" },
  { hangul: "시간", romanization: "sigan", meaning: "time" },
  { hangul: "오늘", romanization: "oneul", meaning: "today" },
  { hangul: "내일", romanization: "naeil", meaning: "tomorrow" },
  { hangul: "어제", romanization: "eoje", meaning: "yesterday" },
  { hangul: "지금", romanization: "jigeum", meaning: "now" },
  { hangul: "손", romanization: "son", meaning: "hand" },
  { hangul: "눈", romanization: "nun", meaning: "eye / snow" },
  { hangul: "입", romanization: "ip", meaning: "mouth" },
  { hangul: "귀", romanization: "gwi", meaning: "ear" },
  { hangul: "발", romanization: "bal", meaning: "foot" },
  { hangul: "머리", romanization: "meori", meaning: "head / hair" },
  { hangul: "마음", romanization: "maeum", meaning: "heart / mind" },
  { hangul: "말", romanization: "mal", meaning: "word / speech" },
  { hangul: "돈", romanization: "don", meaning: "money" },
  { hangul: "책", romanization: "chaek", meaning: "book" },
  { hangul: "차", romanization: "cha", meaning: "car / tea" },
  { hangul: "길", romanization: "gil", meaning: "road / way" },
  { hangul: "문", romanization: "mun", meaning: "door" },
  { hangul: "나라", romanization: "nara", meaning: "country" },
  { hangul: "하늘", romanization: "haneul", meaning: "sky" },
  { hangul: "땅", romanization: "ttang", meaning: "ground / land" },
  { hangul: "바다", romanization: "bada", meaning: "sea" },
  { hangul: "산", romanization: "san", meaning: "mountain" },
  { hangul: "나무", romanization: "namu", meaning: "tree" },
  { hangul: "꽃", romanization: "kkot", meaning: "flower" },
  { hangul: "비", romanization: "bi", meaning: "rain" },
  { hangul: "바람", romanization: "baram", meaning: "wind" },
  { hangul: "불", romanization: "bul", meaning: "fire" },
  { hangul: "음식", romanization: "eumsik", meaning: "food" },
  { hangul: "커피", romanization: "keopi", meaning: "coffee" },
  { hangul: "우유", romanization: "uyu", meaning: "milk" },
  { hangul: "고기", romanization: "gogi", meaning: "meat" },
  { hangul: "과일", romanization: "gwail", meaning: "fruit" },
  { hangul: "채소", romanization: "chaeso", meaning: "vegetable" },
  { hangul: "아침", romanization: "achim", meaning: "morning / breakfast" },
  { hangul: "점심", romanization: "jeomsim", meaning: "lunch" },
  { hangul: "저녁", romanization: "jeonyeok", meaning: "evening / dinner" },
  { hangul: "여기", romanization: "yeogi", meaning: "here" },
  { hangul: "거기", romanization: "geogi", meaning: "there" },
  { hangul: "어디", romanization: "eodi", meaning: "where" },
  { hangul: "무엇", romanization: "mueot", meaning: "what" },
  { hangul: "누구", romanization: "nugu", meaning: "who" },
  { hangul: "언제", romanization: "eonje", meaning: "when" },
  { hangul: "왜", romanization: "wae", meaning: "why" },
  { hangul: "어떻게", romanization: "eotteoke", meaning: "how" },
  { hangul: "사과", romanization: "sagwa", meaning: "apple" },
  { hangul: "학생", romanization: "haksaeng", meaning: "student" },
  { hangul: "선생님", romanization: "seonsaengnim", meaning: "teacher" },
  { hangul: "가족", romanization: "gajok", meaning: "family" },
  { hangul: "엄마", romanization: "eomma", meaning: "mom" },
  { hangul: "아빠", romanization: "appa", meaning: "dad" },
  { hangul: "형", romanization: "hyeong", meaning: "older brother (male's)" },
  { hangul: "누나", romanization: "nuna", meaning: "older sister (male's)" },
  { hangul: "동생", romanization: "dongsaeng", meaning: "younger sibling" },
  { hangul: "아이", romanization: "ai", meaning: "child" },
  { hangul: "남자", romanization: "namja", meaning: "man" },
  { hangul: "여자", romanization: "yeoja", meaning: "woman" },
  { hangul: "이름", romanization: "ireum", meaning: "name" },
  { hangul: "나이", romanization: "nai", meaning: "age" },
  { hangul: "회사", romanization: "hoesa", meaning: "company" },
  { hangul: "일", romanization: "il", meaning: "work / day" },
  { hangul: "가다", romanization: "gada", meaning: "to go" },
  { hangul: "오다", romanization: "oda", meaning: "to come" },
  { hangul: "먹다", romanization: "meokda", meaning: "to eat" },
  { hangul: "마시다", romanization: "masida", meaning: "to drink" },
  { hangul: "자다", romanization: "jada", meaning: "to sleep" },
  { hangul: "보다", romanization: "boda", meaning: "to see / watch" },
  { hangul: "듣다", romanization: "deutda", meaning: "to listen" },
  { hangul: "말하다", romanization: "malhada", meaning: "to speak" },
  { hangul: "읽다", romanization: "ikda", meaning: "to read" },
  { hangul: "쓰다", romanization: "sseuda", meaning: "to write / use" },
  { hangul: "사다", romanization: "sada", meaning: "to buy" },
  { hangul: "주다", romanization: "juda", meaning: "to give" },
  { hangul: "받다", romanization: "batda", meaning: "to receive" },
  { hangul: "좋다", romanization: "jota", meaning: "to be good" },
  { hangul: "나쁘다", romanization: "nappeuda", meaning: "to be bad" },
  { hangul: "크다", romanization: "keuda", meaning: "to be big" },
  { hangul: "작다", romanization: "jakda", meaning: "to be small" },
  { hangul: "많다", romanization: "manta", meaning: "to be many" },
  { hangul: "예쁘다", romanization: "yeppeuda", meaning: "to be pretty" },
  { hangul: "행복", romanization: "haengbok", meaning: "happiness" },
  { hangul: "사랑하다", romanization: "saranghada", meaning: "to love" },
  { hangul: "좋아하다", romanization: "joahada", meaning: "to like" },
  { hangul: "알다", romanization: "alda", meaning: "to know" },
  { hangul: "모르다", romanization: "moreuda", meaning: "to not know" },
  { hangul: "생각", romanization: "saenggak", meaning: "thought" },
  { hangul: "웃다", romanization: "utda", meaning: "to laugh / smile" },
  { hangul: "기다리다", romanization: "gidarida", meaning: "to wait" },
];

// Returns the word for a given day, rotating deterministically by date so it is
// stable across reloads and the same for the whole day.
export function getWordOfTheDay(date: Date = new Date()): KoreanWord {
  const dayNumber = Math.floor(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86400000
  );
  return KOREAN_WORDS[((dayNumber % KOREAN_WORDS.length) + KOREAN_WORDS.length) % KOREAN_WORDS.length];
}
