// 100 of the most common / useful beginner Korean words.
// One is surfaced per day on the dashboard, rotating by date.

export interface KoreanWord {
  hangul: string;
  romanization: string;
  meaning: string;
  // Plain-English "sound it out" guide for an American speaker. Hyphens split
  // syllables; CAPS marks the syllable to lean on slightly.
  sound: string;
}

export const KOREAN_WORDS: KoreanWord[] = [
  { hangul: "안녕", romanization: "annyeong", meaning: "hello / hi", sound: "ahn-NYUNG (rhymes with 'young')" },
  { hangul: "네", romanization: "ne", meaning: "yes", sound: "NEH (like 'net' without the t)" },
  { hangul: "아니요", romanization: "aniyo", meaning: "no", sound: "AH-nee-yoh" },
  { hangul: "감사합니다", romanization: "gamsahamnida", meaning: "thank you", sound: "gahm-sah-HAHM-nee-dah" },
  { hangul: "사랑", romanization: "sarang", meaning: "love", sound: "sah-RAHNG" },
  { hangul: "물", romanization: "mul", meaning: "water", sound: "MOOL (like 'mool' in 'moo' + 'l')" },
  { hangul: "밥", romanization: "bap", meaning: "rice / meal", sound: "BAHP" },
  { hangul: "사람", romanization: "saram", meaning: "person", sound: "SAH-rahm" },
  { hangul: "집", romanization: "jip", meaning: "house / home", sound: "JEEP" },
  { hangul: "학교", romanization: "hakgyo", meaning: "school", sound: "HAHK-gyoh" },
  { hangul: "친구", romanization: "chingu", meaning: "friend", sound: "CHEEN-goo" },
  { hangul: "시간", romanization: "sigan", meaning: "time", sound: "SHEE-gahn" },
  { hangul: "오늘", romanization: "oneul", meaning: "today", sound: "OH-nuhl" },
  { hangul: "내일", romanization: "naeil", meaning: "tomorrow", sound: "NEH-eel" },
  { hangul: "어제", romanization: "eoje", meaning: "yesterday", sound: "UH-jeh" },
  { hangul: "지금", romanization: "jigeum", meaning: "now", sound: "JEE-gum" },
  { hangul: "손", romanization: "son", meaning: "hand", sound: "SOHN" },
  { hangul: "눈", romanization: "nun", meaning: "eye / snow", sound: "NOON" },
  { hangul: "입", romanization: "ip", meaning: "mouth", sound: "EEP" },
  { hangul: "귀", romanization: "gwi", meaning: "ear", sound: "GWEE" },
  { hangul: "발", romanization: "bal", meaning: "foot", sound: "BAHL" },
  { hangul: "머리", romanization: "meori", meaning: "head / hair", sound: "MUH-ree" },
  { hangul: "마음", romanization: "maeum", meaning: "heart / mind", sound: "MAH-oom" },
  { hangul: "말", romanization: "mal", meaning: "word / speech", sound: "MAHL" },
  { hangul: "돈", romanization: "don", meaning: "money", sound: "DOHN" },
  { hangul: "책", romanization: "chaek", meaning: "book", sound: "CHEK (like 'check')" },
  { hangul: "차", romanization: "cha", meaning: "car / tea", sound: "CHAH" },
  { hangul: "길", romanization: "gil", meaning: "road / way", sound: "GEEL" },
  { hangul: "문", romanization: "mun", meaning: "door", sound: "MOON" },
  { hangul: "나라", romanization: "nara", meaning: "country", sound: "NAH-rah" },
  { hangul: "하늘", romanization: "haneul", meaning: "sky", sound: "HAH-nuhl" },
  { hangul: "땅", romanization: "ttang", meaning: "ground / land", sound: "DDAHNG (hard, tense 't')" },
  { hangul: "바다", romanization: "bada", meaning: "sea", sound: "BAH-dah" },
  { hangul: "산", romanization: "san", meaning: "mountain", sound: "SAHN" },
  { hangul: "나무", romanization: "namu", meaning: "tree", sound: "NAH-moo" },
  { hangul: "꽃", romanization: "kkot", meaning: "flower", sound: "GGOHT (tense 'k', stop the t)" },
  { hangul: "비", romanization: "bi", meaning: "rain", sound: "BEE" },
  { hangul: "바람", romanization: "baram", meaning: "wind", sound: "BAH-rahm" },
  { hangul: "불", romanization: "bul", meaning: "fire", sound: "BOOL" },
  { hangul: "음식", romanization: "eumsik", meaning: "food", sound: "OOM-sheek" },
  { hangul: "커피", romanization: "keopi", meaning: "coffee", sound: "KUH-pee" },
  { hangul: "우유", romanization: "uyu", meaning: "milk", sound: "OO-yoo" },
  { hangul: "고기", romanization: "gogi", meaning: "meat", sound: "GOH-gee" },
  { hangul: "과일", romanization: "gwail", meaning: "fruit", sound: "GWAH-eel" },
  { hangul: "채소", romanization: "chaeso", meaning: "vegetable", sound: "CHEH-soh" },
  { hangul: "아침", romanization: "achim", meaning: "morning / breakfast", sound: "AH-cheem" },
  { hangul: "점심", romanization: "jeomsim", meaning: "lunch", sound: "JUHM-sheem" },
  { hangul: "저녁", romanization: "jeonyeok", meaning: "evening / dinner", sound: "JUH-nyuhk" },
  { hangul: "여기", romanization: "yeogi", meaning: "here", sound: "YUH-gee" },
  { hangul: "거기", romanization: "geogi", meaning: "there", sound: "GUH-gee" },
  { hangul: "어디", romanization: "eodi", meaning: "where", sound: "UH-dee" },
  { hangul: "무엇", romanization: "mueot", meaning: "what", sound: "MOO-uht" },
  { hangul: "누구", romanization: "nugu", meaning: "who", sound: "NOO-goo" },
  { hangul: "언제", romanization: "eonje", meaning: "when", sound: "UHN-jeh" },
  { hangul: "왜", romanization: "wae", meaning: "why", sound: "WEH (like 'where' without the r)" },
  { hangul: "어떻게", romanization: "eotteoke", meaning: "how", sound: "uh-DDUH-keh" },
  { hangul: "사과", romanization: "sagwa", meaning: "apple", sound: "SAH-gwah" },
  { hangul: "학생", romanization: "haksaeng", meaning: "student", sound: "HAHK-sehng" },
  { hangul: "선생님", romanization: "seonsaengnim", meaning: "teacher", sound: "suhn-SEHNG-neem" },
  { hangul: "가족", romanization: "gajok", meaning: "family", sound: "GAH-johk" },
  { hangul: "엄마", romanization: "eomma", meaning: "mom", sound: "UHM-mah" },
  { hangul: "아빠", romanization: "appa", meaning: "dad", sound: "AH-bbah (tense 'p')" },
  { hangul: "형", romanization: "hyeong", meaning: "older brother (male's)", sound: "HYUHNG" },
  { hangul: "누나", romanization: "nuna", meaning: "older sister (male's)", sound: "NOO-nah" },
  { hangul: "동생", romanization: "dongsaeng", meaning: "younger sibling", sound: "DOHNG-sehng" },
  { hangul: "아이", romanization: "ai", meaning: "child", sound: "AH-ee (like 'eye' stretched)" },
  { hangul: "남자", romanization: "namja", meaning: "man", sound: "NAHM-jah" },
  { hangul: "여자", romanization: "yeoja", meaning: "woman", sound: "YUH-jah" },
  { hangul: "이름", romanization: "ireum", meaning: "name", sound: "EE-room" },
  { hangul: "나이", romanization: "nai", meaning: "age", sound: "NAH-ee" },
  { hangul: "회사", romanization: "hoesa", meaning: "company", sound: "HWEH-sah" },
  { hangul: "일", romanization: "il", meaning: "work / day", sound: "EEL" },
  { hangul: "가다", romanization: "gada", meaning: "to go", sound: "GAH-dah" },
  { hangul: "오다", romanization: "oda", meaning: "to come", sound: "OH-dah" },
  { hangul: "먹다", romanization: "meokda", meaning: "to eat", sound: "MUHK-dah" },
  { hangul: "마시다", romanization: "masida", meaning: "to drink", sound: "MAH-shee-dah" },
  { hangul: "자다", romanization: "jada", meaning: "to sleep", sound: "JAH-dah" },
  { hangul: "보다", romanization: "boda", meaning: "to see / watch", sound: "BOH-dah" },
  { hangul: "듣다", romanization: "deutda", meaning: "to listen", sound: "DOOT-dah" },
  { hangul: "말하다", romanization: "malhada", meaning: "to speak", sound: "mahl-HAH-dah" },
  { hangul: "읽다", romanization: "ikda", meaning: "to read", sound: "EEK-dah" },
  { hangul: "쓰다", romanization: "sseuda", meaning: "to write / use", sound: "SSOO-dah (tense 's')" },
  { hangul: "사다", romanization: "sada", meaning: "to buy", sound: "SAH-dah" },
  { hangul: "주다", romanization: "juda", meaning: "to give", sound: "JOO-dah" },
  { hangul: "받다", romanization: "batda", meaning: "to receive", sound: "BAHT-dah" },
  { hangul: "좋다", romanization: "jota", meaning: "to be good", sound: "JOH-tah" },
  { hangul: "나쁘다", romanization: "nappeuda", meaning: "to be bad", sound: "nah-BBOO-dah" },
  { hangul: "크다", romanization: "keuda", meaning: "to be big", sound: "KOO-dah (lips unrounded)" },
  { hangul: "작다", romanization: "jakda", meaning: "to be small", sound: "JAHK-dah" },
  { hangul: "많다", romanization: "manta", meaning: "to be many", sound: "MAHN-tah" },
  { hangul: "예쁘다", romanization: "yeppeuda", meaning: "to be pretty", sound: "yeh-BBOO-dah" },
  { hangul: "행복", romanization: "haengbok", meaning: "happiness", sound: "HEHNG-bohk" },
  { hangul: "사랑하다", romanization: "saranghada", meaning: "to love", sound: "sah-rahng-HAH-dah" },
  { hangul: "좋아하다", romanization: "joahada", meaning: "to like", sound: "joh-AH-hah-dah" },
  { hangul: "알다", romanization: "alda", meaning: "to know", sound: "AHL-dah" },
  { hangul: "모르다", romanization: "moreuda", meaning: "to not know", sound: "moh-ROO-dah" },
  { hangul: "생각", romanization: "saenggak", meaning: "thought", sound: "SEHNG-gahk" },
  { hangul: "웃다", romanization: "utda", meaning: "to laugh / smile", sound: "OOT-dah" },
  { hangul: "기다리다", romanization: "gidarida", meaning: "to wait", sound: "gee-dah-REE-dah" },
];

// Returns the word for a given day, rotating deterministically by date so it is
// stable across reloads and the same for the whole day.
export function getWordOfTheDay(date: Date = new Date()): KoreanWord {
  const dayNumber = Math.floor(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / 86400000
  );
  return KOREAN_WORDS[((dayNumber % KOREAN_WORDS.length) + KOREAN_WORDS.length) % KOREAN_WORDS.length];
}
