// A second batch for the popular-quote pool, added when one account stopped
// getting the calendar quote and started drawing every day's quote from the
// pool — at that rate the first batch would run dry within the year.
//
// Same rule as popularQuotes.ts: commonly accepted attributions only, and
// quotes known to be misattributed are left out.

import type { PopularQuote } from "./popularQuotes";

export const MORE_QUOTES: PopularQuote[] = [
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Lao Tzu" },
  { text: "While we wait for life, life passes.", author: "Seneca" },
  { text: "I think, therefore I am.", author: "René Descartes" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "To thine own self be true.", author: "William Shakespeare" },
  { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
  { text: "There is nothing either good or bad, but thinking makes it so.", author: "William Shakespeare" },
  { text: "Dwell in possibility.", author: "Emily Dickinson" },
  { text: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "I am not afraid of storms, for I am learning how to sail my ship.", author: "Louisa May Alcott" },
  { text: "The most courageous act is still to think for yourself. Aloud.", author: "Coco Chanel" },
  { text: "A girl should be two things: who and what she wants.", author: "Coco Chanel" },
  { text: "I have learned over the years that when one's mind is made up, this diminishes fear.", author: "Rosa Parks" },
  { text: "We do not remember days, we remember moments.", author: "Cesare Pavese" },
  { text: "The purpose of life is to live it, to taste experience to the utmost.", author: "Eleanor Roosevelt" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { text: "Be quick, but don't hurry.", author: "John Wooden" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "Pressure is a privilege.", author: "Billie Jean King" },
  { text: "The good thing about science is that it's true whether or not you believe in it.", author: "Neil deGrasse Tyson" },
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { text: "The way to get good ideas is to get lots of ideas and throw the bad ones away.", author: "Linus Pauling" },
  { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
  { text: "What would you do if you weren't afraid?", author: "Sheryl Sandberg" },
  { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
  { text: "A smooth sea never made a skilled sailor.", author: "English proverb" },
  { text: "When the student is ready, the teacher will appear.", author: "Buddhist proverb" },
  { text: "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", author: "Rumi" },
  { text: "Out beyond ideas of wrongdoing and rightdoing there is a field. I'll meet you there.", author: "Rumi" },
  { text: "Vulnerability is the birthplace of innovation, creativity and change.", author: "Brené Brown" },
  { text: "There are two ways of spreading light: to be the candle or the mirror that reflects it.", author: "Edith Wharton" },
  { text: "Do I contradict myself? Very well then I contradict myself, (I am large, I contain multitudes.)", author: "Walt Whitman" },
  { text: "Ideas are like rabbits. You get a couple and learn how to handle them, and pretty soon you have a dozen.", author: "John Steinbeck" },
  { text: "Today you are You, that is truer than true. There is no one alive who is Youer than You.", author: "Dr. Seuss" },
  { text: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },
  { text: "Unless someone like you cares a whole awful lot, nothing is going to get better. It's not.", author: "Dr. Seuss" },
  { text: "If you look the right way, you can see that the whole world is a garden.", author: "Frances Hodgson Burnett" },
  { text: "It does not do to dwell on dreams and forget to live.", author: "J.K. Rowling" },
  { text: "What is essential is invisible to the eye.", author: "Antoine de Saint-Exupéry" },
  { text: "The world breaks everyone and afterward many are strong at the broken places.", author: "Ernest Hemingway" },
  { text: "Rest is not idleness.", author: "John Lubbock" },
  { text: "If you have a garden and a library, you have everything you need.", author: "Cicero" },
  { text: "Joy is the simplest form of gratitude.", author: "Karl Barth" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "You are the sky. Everything else is just the weather.", author: "Pema Chödrön" },
  { text: "Nothing ever goes away until it has taught us what we need to know.", author: "Pema Chödrön" },
  { text: "Out of difficulties grow miracles.", author: "Jean de La Bruyère" },
  { text: "Whatever you do, do it well.", author: "Walt Disney" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { text: "Don't cry because it's over, smile because it happened.", author: "Ludwig Jacobowski" },
  { text: "To love oneself is the beginning of a lifelong romance.", author: "Oscar Wilde" },
  { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddhist teaching" },
  { text: "There is no path to happiness: happiness is the path.", author: "Buddhist teaching" },
  { text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { text: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { text: "It is good to have an end to journey toward; but it is the journey that matters, in the end.", author: "Ursula K. Le Guin" },
  { text: "The creative adult is the child who survived.", author: "Ursula K. Le Guin" },
  { text: "I can be changed by what happens to me. But I refuse to be reduced by it.", author: "Maya Angelou" },
  { text: "My mission in life is not merely to survive, but to thrive.", author: "Maya Angelou" },
  { text: "You may encounter many defeats, but you must not be defeated.", author: "Maya Angelou" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Success is nothing more than a few simple disciplines, practiced every day.", author: "Jim Rohn" },
  { text: "We must all suffer one of two things: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { text: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
  { text: "The greatest danger to our future is apathy.", author: "Jane Goodall" },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus" },
  { text: "Autumn is a second spring when every leaf is a flower.", author: "Albert Camus" },
  { text: "Be patient toward all that is unsolved in your heart and try to love the questions themselves.", author: "Rainer Maria Rilke" },
  { text: "Let everything happen to you: beauty and terror. Just keep going. No feeling is final.", author: "Rainer Maria Rilke" },
  { text: "Live the questions now.", author: "Rainer Maria Rilke" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "I am not what happened to me, I am what I choose to become.", author: "Carl Jung" },
  { text: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung" },
  { text: "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.", author: "Carl Jung" },
  { text: "Attention is the rarest and purest form of generosity.", author: "Simone Weil" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { text: "If you judge people, you have no time to love them.", author: "Mother Teresa" },
  { text: "Peace begins with a smile.", author: "Mother Teresa" },
  { text: "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.", author: "Dalai Lama" },
  { text: "Sleep is the best meditation.", author: "Dalai Lama" },
  { text: "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", author: "Samuel Beckett" },
  { text: "Courage is not the absence of fear, but rather the judgment that something else is more important than fear.", author: "Ambrose Redmoon" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { text: "Never be so busy as not to think of others.", author: "Mother Teresa" },
  { text: "It's never crowded along the extra mile.", author: "Wayne Dyer" },
  { text: "If you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
  { text: "You can't connect the dots looking forward; you can only connect them looking backwards.", author: "Steve Jobs" },
  { text: "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.", author: "Steve Jobs" },
  { text: "It's not about ideas. It's about making ideas happen.", author: "Scott Belsky" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard" },
  { text: "Do not take life too seriously. You will never get out of it alive.", author: "Elbert Hubbard" },
  { text: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese proverb" },
  { text: "Even monkeys fall from trees.", author: "Japanese proverb" },
  { text: "When you drink water, remember the spring.", author: "Chinese proverb" },
  { text: "A smile is the light in your window that tells others there is a caring, sharing person inside.", author: "Denis Waitley" },
  { text: "Mistakes are the portals of discovery.", author: "James Joyce" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Where focus goes, energy flows.", author: "Tony Robbins" },
  { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
  { text: "If it doesn't challenge you, it won't change you.", author: "Fred DeVito" },
  { text: "The secret of your future is hidden in your daily routine.", author: "Mike Murdock" },
  { text: "You become what you give your attention to.", author: "Epictetus" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "As is a tale, so is life: not how long it is, but how good it is, is what matters.", author: "Seneca" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius" },
  { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius" },
  { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", author: "Marcus Aurelius" },
  { text: "Pleasure in the job puts perfection in the work.", author: "Aristotle" },
  { text: "Let us cultivate our garden.", author: "Voltaire" },
  { text: "Perfect is the enemy of good.", author: "Voltaire" },
  { text: "Nothing great in the world has ever been accomplished without passion.", author: "Georg Wilhelm Friedrich Hegel" },
  { text: "The heart has its reasons which reason knows nothing of.", author: "Blaise Pascal" },
  { text: "Two things fill the mind with ever new and increasing admiration and awe: the starry heavens above me and the moral law within me.", author: "Immanuel Kant" },
  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { text: "One must still have chaos in oneself to be able to give birth to a dancing star.", author: "Friedrich Nietzsche" },
  { text: "Life can only be understood backwards; but it must be lived forwards.", author: "Søren Kierkegaard" },
  { text: "Anxiety is the dizziness of freedom.", author: "Søren Kierkegaard" },
];
