import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UpdatePill from "./UpdatePill";
import ServiceWorkerRegistrar from "./ServiceWorkerRegistrar";
import splashScreens from "./splash-screens.json";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Gratitude Journal",
  description: "A calm space to reflect on what you're grateful for, every day.",
  applicationName: "Gratitude",
  // Tells iOS to launch from the home screen without Safari's chrome. The
  // manifest's `display` covers everything else; iOS still wants this.
  appleWebApp: {
    capable: true,
    title: "Gratitude",
    // `default` keeps the status bar dark-on-light, which is what the cream
    // background needs. `black-translucent` would put the clock on top of the
    // header.
    statusBarStyle: "default",
  },
  icons: {
    icon: [{ url: "/icons/favicon-32.png", sizes: "32x32", type: "image/png" }],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180" }],
  },
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Lets the app paint into the notch and home-indicator areas; the padding is
  // handed back deliberately via env(safe-area-inset-*) in globals.css.
  viewportFit: "cover",
  themeColor: "#faf8f5",
  // Deliberately NOT user-scalable: false — pinch-zoom stays available, and the
  // 16px input floor in globals.css is what stops iOS auto-zooming on focus.
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* iOS launch images. Generated by scripts/generate-app-icons.mjs, and
            listed from that script's output so the tags can't drift from the
            files. Without an exact media match iOS shows a white flash. */}
        {splashScreens.map((entry) => {
          const [media, href] = entry.split("|");
          return <link key={href} rel="apple-touch-startup-image" media={media} href={href} />;
        })}
      </head>
      <body className={`${inter.variable} min-h-screen`}>
        {children}
        <UpdatePill />
        <ServiceWorkerRegistrar />
      </body>
    </html>
  );
}
